export default [
  {
    id: 3,
    img: "/product__1.png",
    name: "Mascara Volume Boost",
    price: 28.75,
    category: ["mascara", "lipsticks"],
    sale: true,
  },
  {
    id: 5,
    img: "/product__3.png",
    name: "Hydrating Facial Mist",
    price: 15.0,
    category: ["skincare", "makeup"],
    sale: false,
  },
  {
    id: 1,
    img: "/product__2.png",
    name: "Matte Red Lipstick",
    price: 35.99,
    category: ["lipsticks"],
    sale: true,
  },
  {
    id: 7,
    img: "/product__4.png",
    name: "Gel Eyeliner Black",
    price: 18.5,
    category: ["eyeliner"],
    sale: false,
  },
  {
    id: 14,
    img: "/product__5.png",
    name: "Cleansing Oil Makeup Remover",
    price: 14.99,
    category: ["skincare"],
    sale: true,
  },
  {
    id: 0,
    img: "/product__6.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 11,
    img: "/product__3.png",
    name: "Curl Enhancing Shampoo",
    price: 30.5,
    category: ["haircare", "skincare"],
    sale: false,
  },
  {
    id: 15,
    img: "/product__1.png",
    name: "Long-Lasting Nail Polish",
    price: 9.5,
    category: ["nailcare", "lipsticks"],
    sale: false,
  },
  {
    id: 9,
    img: "/product__2.png",
    name: "Anti-Aging Night Cream",
    price: 45.99,
    category: ["skincare", "lipsticks"],
    sale: true,
  },
  {
    id: 13,
    img: "/product__6.png",
    name: "Sun-Kissed Bronzer",
    price: 21.0,
    category: ["bronzer"],
    sale: false,
  },
  {
    id: 10,
    img: "/product__4.png",
    name: "Sculpting Brow Pencil",
    price: 14.75,
    category: ["brows"],
    sale: false,
  },
  {
    id: 4,
    img: "/product__5.png",
    name: "Rose Petal Blush",
    price: 19.99,
    category: ["blush", "makeup"],
    sale: false,
  },
  {
    id: 2,
    img: "/product__3.png",
    name: "Natural Glow Foundation",
    price: 55.5,
    category: ["makeup", "skincare"],
    sale: false,
  },
  {
    id: 8,
    img: "/product__6.png",
    name: "Moisture Lock Lip Balm",
    price: 12.0,
    category: ["lipcare", "skincare"],
    sale: false,
  },
  {
    id: 6,
    img: "/product__1.png",
    name: "Volumizing Hair Spray",
    price: 22.5,
    category: ["haircare", "lipsticks"],
    sale: true,
  },
  {
    id: 12,
    img: "/product__2.png",
    name: "Pore-Refining Toner",
    price: 17.25,
    category: ["skincare", "lipsticks"],
    sale: true,
  },
   {
    id: 16,
    img: "/product__4.png",
    name: "Dramatic Volume Mascara",
    price: 24.5,
    category: ["mascara"],
    sale: true,
  },
  {
    id: 17,
    img: "/product__5.png",
    name: "Radiant Glow Primer",
    price: 29.99,
    category: ["primer", "makeup"],
    sale: false,
  },
  {
    id: 18,
    img: "/product__1.png",
    name: "Curl Defining Cream",
    price: 17.0,
    category: ["haircare"],
    sale: false,
  },
  {
    id: 19,
    img: "/product__2.png",
    name: "Precision Liquid Eyeliner",
    price: 16.25,
    category: ["eyeliner"],
    sale: true,
  },
  {
    id: 20,
    img: "/product__3.png",
    name: "Soothing Aloe Vera Gel",
    price: 12.5,
    category: ["skincare"],
    sale: false,
  },
  {
    id: 21,
    img: "/product__4.png",
    name: "Nourishing Lip Scrub",
    price: 13.99,
    category: ["lipcare"],
    sale: true,
  },
  {
    id: 22,
    img: "/product__5.png",
    name: "Volume-Boosting Conditioner",
    price: 19.5,
    category: ["haircare"],
    sale: false,
  },
  {
    id: 23,
    img: "/product__6.png",
    name: "Waterproof Brow Gel",
    price: 21.75,
    category: ["brows"],
    sale: false,
  },
  {
    id: 24,
    img: "/product__1.png",
    name: "Refreshing Facial Cleanser",
    price: 15.0,
    category: ["skincare"],
    sale: true,
  },
  {
    id: 25,
    img: "/product__2.png",
    name: "Shimmering Body Lotion",
    price: 18.99,
    category: ["bodycare"],
    sale: false,
  },
  {
    id: 26,
    img: "/product__3.png",
    name: "Elegant Nude Eyeshadow Palette",
    price: 32.5,
    category: ["eyeshadow", "makeup"],
    sale: true,
  },
  {
    id: 27,
    img: "/product__4.png",
    name: "Revitalizing Scalp Treatment",
    price: 23.0,
    category: ["haircare"],
    sale: false,
  },
  {
    id: 28,
    img: "/product__6.png",
    name: "Gentle Exfoliating Scrub",
    price: 14.5,
    category: ["skincare"],
    sale: false,
  },
  {
    id: 29,
    img: "/product__5.png",
    name: "Satin Finish Nail Polish",
    price: 11.99,
    category: ["nailcare"],
    sale: true,
  },
  {
    id: 30,
    img: "/product__1.png",
    name: "Luminous Highlighter",
    price: 27.5,
    category: ["highlighter", "makeup"],
    sale: false,
  },
];
